version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: fawedding_postgres
    restart: always
    environment:
      POSTGRES_USER: fawedding
      POSTGRES_PASSWORD: fawedding123
      POSTGRES_DB: fawedding_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: