version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: fawedding_postgres
    restart: always
    environment:
      POSTGRES_USER: fawedding
      POSTGRES_PASSWORD: fawedding123
      POSTGRES_DB: fawedding_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: fawedding_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fawedding.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data: